# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"]\n\nTrackPoint\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x12\n\ncourse_sin\x18\x04 \x01(\x02\x12\x12\n\ncourse_cos\x18\x05 \x01(\x02\"\'\n\x0b\x46uturePoint\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\"8\n\x0ePredictRequest\x12&\n\x07history\x18\x01 \x03(\x0b\x32\x15.inference.TrackPoint\"=\n\x0fPredictResponse\x12*\n\nprediction\x18\x01 \x03(\x0b\x32\x16.inference.FuturePoint\"A\n\x13PredictBatchRequest\x12*\n\x07vessels\x18\x01 \x03(\x0b\x32\x19.inference.PredictRequest\"G\n\x14PredictBatchResponse\x12/\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1a.inference.PredictResponse\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xdd\x01\n\tInference\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12O\n\x0cPredictBatch\x12\x1e.inference.PredictBatchRequest\x1a\x1f.inference.PredictBatchResponse\x12=\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKPOINT']._serialized_start=30
  _globals['_TRACKPOINT']._serialized_end=123
  _globals['_FUTUREPOINT']._serialized_start=125
  _globals['_FUTUREPOINT']._serialized_end=164
  _globals['_PREDICTREQUEST']._serialized_start=166
  _globals['_PREDICTREQUEST']._serialized_end=222
  _globals['_PREDICTRESPONSE']._serialized_start=224
  _globals['_PREDICTRESPONSE']._serialized_end=285
  _globals['_PREDICTBATCHREQUEST']._serialized_start=287
  _globals['_PREDICTBATCHREQUEST']._serialized_end=352
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=354
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=425
  _globals['_HEALTHREQUEST']._serialized_start=427
  _globals['_HEALTHREQUEST']._serialized_end=442
  _globals['_HEALTHRESPONSE']._serialized_start=444
  _globals['_HEALTHRESPONSE']._serialized_end=476
  _globals['_INFERENCE']._serialized_start=479
  _globals['_INFERENCE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
